In [2]:
# Vector
x = [1, 2]
# Matrix
A =[[1, 2], [3, 4]]
# Tensor
T = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [6]:
# Norm of Tensor
A = [   [[1, 0, 1, 0], [2, 1, 0, 1], [3, 4, 0, 2]],
        [[3, 1, 2, 0], [1, 0, 4, 2], [0, 1, 0, 2]]  ]

n = len(A[0])
p = len(A[0][0])
q = len(A)
print(n, p, q)

norm = 0
for i in range(n):
  for j in range(p):
    for k in range(q):
      norm += A[k][i][j]**2
norm = norm ** 0.5

print(norm)

3 4 2
8.774964387392123


In [7]:
# Inner Product of Tensor
A = [   [[1, 0, 1, 0], [2, 1, 0, 1], [3, 4, 0, 2]],
        [[3, 1, 2, 0], [1, 0, 4, 2], [0, 1, 0, 2]]  ]
B = [   [[2, 1, 3, 1], [0, 2, 1, 3], [1, 0, 1, 1]],
        [[1, 2, 3, 1], [3, 1, 0, 3], [0, 2, 3, 1]]  ]

n = len(A[0])
p = len(A[0][0])
q = len(A)

inner_product = 0
for i in range(n):
  for j in range(p):
    for k in range(q):
      inner_product += A[k][i][j] * B[k][i][j]
  
print(inner_product)

39


In [10]:
# Inner Product of Tensor by Numpy
import numpy as np

A = np.array([  [[1, 0, 1, 0], [2, 1, 0, 1], [3, 4, 0, 2]],
                [[3, 1, 2, 0], [1, 0, 4, 2], [0, 1, 0, 2]]  ])
B = np.array([  [[2, 1, 3, 1], [0, 2, 1, 3], [1, 0, 1, 1]],
                [[1, 2, 3, 1], [3, 1, 0, 3], [0, 2, 3, 1]]  ])

C = np.multiply(A, B)
print(C)

inner_product = np.sum(C)
print(inner_product)

[[[2 0 3 0]
  [0 2 0 3]
  [3 0 0 2]]

 [[3 2 6 0]
  [3 0 0 6]
  [0 2 0 2]]]
39


In [ ]:
# Tensor to Matrix
A = [   [[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]],
        [[13, 16, 19 ,22], [14, 17, 20, 23], [15, 18, 21, 24]]  ]

n = len(A[0])
p = len(A[0][0])
q = len(A)

model = []
for i in range(n):
  row = []
  for j in range(p):
    for k in range(q):
      row.append(A[k][i][j])
    