matrix 는 행렬, 행과 열로 이루어져 있음

행(=row) - 가로 방향

열(=column) - 세로 방향


1. Matrix Element Multiplication

2. Matrix Multiplication(if u.row == v.col)

if u.row == u.col == v.row == v.col -> 교환법칙 성립

Matrix Trace(행렬의 대각합)

정사각 행렬일때만 성립

A =

  a11 a12 a13

  a21 a22 a23

  a31 a32 a33

  tr(A) = a11 + a22+ a 33

In [2]:
import numpy as np

A = np.array([[2, 7], [3, 4], [6,1]])
B = np.array([[1, 4], [4, -1], [2, 5]])

C = A + B
print(C)

C = A - B
print(C)

# 행렬의 원소 곱
C = np.multiply(A, B)
print(C)

# 행렬 곱
A = np.array([[2, 7], [3, 4], [5, 2]])
B = np.array([[3, -3, 5], [-1, 2, -1]])
C = np.matmul(A, B)
print(C)

[[ 3 11]
 [ 7  3]
 [ 8  6]]
[[ 1  3]
 [-1  5]
 [ 4 -4]]
[[ 2 28]
 [12 -4]
 [12  5]]
[[ -1   8   3]
 [  5  -1  11]
 [ 13 -11  23]]


Transposed Matrix(전치행렬)

기존의 행렬의 행과 열을 바꾼 행렬
 - 행번호가 열번호로, 열번호가 행번호로
 

In [4]:
A = np.array([[1, 5], [3, 4], [6, 2]])
#At = np.transpose(A)
At = A.T
print(A)
print(At)

[[1 5]
 [3 4]
 [6 2]]
[[1 3 6]
 [5 4 2]]


Symmetric Matrix(대칭 행렬)

기존행렬과 전치행렬이 동일한 정사각 행렬

A =

  a, b, c

  b, d, e

  c, e, f


A = At

Digonal Matrix(대각 행렬)

행렬의 주 대각 원소가 아닌 원소가 0인 정사각 행렬

Identify Matrix(단위 행렬)

주 대각 원소가 1이고 그 밖에 나머지 원소가 모두 0인 행렬

Zero Matirx(영행렬)

행렬의 모든 구성 요소가 0

Triangular Matrix(삼각 행렬)

행렬의 구성 요소가 삼각형 형태를 나타냄

상삼각 / 하삼각 으로 구분

Toepliz Matrix(토플리츠 행렬)

  - a b c d e
  - f a b c d
  - g f a b c
  - h g f a b
  - i h g f a

Ti,j = Ti+1,j+1 = ti-j

In [5]:
from scipy.linalg import toeplitz

A = toeplitz([1, 0, -2, -4], [1, 3, 5, 7, 9])
print(A)

[[ 1  3  5  7  9]
 [ 0  1  3  5  7]
 [-2  0  1  3  5]
 [-4 -2  0  1  3]]


Bidiagonal Matrix(이중 대각 행렬)

대각 원소뿐만아니라 위(upper) 혹은 아래(lower) 원소가 0이 아닌 행렬

In [6]:
A = np.array([[1, 2, 1, 3,], [5, 3, 4, 1], [2, 1, 7, 9], [2, 8, 1, 3]])
print(A)

[[1 2 1 3]
 [5 3 4 1]
 [2 1 7 9]
 [2 8 1 3]]


In [8]:
diag_ele = np.diag(A)
print(diag_ele)

[1 3 7 3]


In [9]:
np.diag(diag_ele)

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 3]])

In [10]:
u_diag_ele = np.diag(A, k=1)
print(u_diag_ele)

[2 4 9]


In [11]:
np.diag(u_diag_ele, k=1)

array([[0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 9],
       [0, 0, 0, 0]])

In [12]:
u_diag = np.diag(diag_ele) + np.diag(u_diag_ele, k=1)
print(u_diag)

[[1 2 0 0]
 [0 3 4 0]
 [0 0 7 9]
 [0 0 0 3]]


Householder matrix(하우스홀더 행렬)

정사각 행렬이며 모든 열이 정규 직교(orthonomal)하는 행렬

H = I - 2 * vvT/vTv


In [14]:
import numpy as np

v = np.array([1, 0, 2, 3])
n = len(v)
#vvT
outer_mat = np.outer(v, v)
print(outer_mat)

[[1 0 2 3]
 [0 0 0 0]
 [2 0 4 6]
 [3 0 6 9]]


In [15]:
#vTv
inner_val = np.inner(v, v)
print(inner_val)

14


In [16]:
#단위 행렬 생성
I = np.identity(n)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
H = I - (2/inner_val)*outer_mat
print(H)

[[ 0.85714286  0.         -0.28571429 -0.42857143]
 [ 0.          1.          0.          0.        ]
 [-0.28571429  0.          0.42857143 -0.85714286]
 [-0.42857143  0.         -0.85714286 -0.28571429]]
